### ISSUE TITLE
Something goes wrong when my podspec declare like this

### ISSUE THREAD

**Issue by Detailscool** [sergeykhliustin/BazelPods#119]
mrc_files = "path/MRC/\*\*/\*.\*"
  s.subspec 'MRC' do |ss|
    ss.requires_arc    = false;
    ss.source_files    = mrc_files
  end
  s.source_files =  "path/\*\*/\*.\*"
  s.exclude_files = mrc_files

non_arc_srcs with mrc_files  should in BUILD.blz

**Comment by Detailscool** [comment]
mrc_files = "path/MRC/\*.\*"
s.subspec 'MRC' do |ss|
ss.requires_arc = false;
ss.source_files = mrc_files
end
s.source_files = "path/\*\*/\*.\*"
s.exclude_files = mrc_files

non_arc_srcs is not in BUILD.blz

**Comment by sergeykhliustin** [comment]
could you please provide your full podspec?
and generated BUILD.bazel
